"""Deterministic stand-in for a real completion provider.

Exists so the POC demonstrates the full prompt flow with no API key, no network
and no per-run cost - and so the AI endpoints stay testable without stubbing
HTTP. It implements the same `LlmProvider` protocol as the Cerebras adapter, so
the only thing that changes between them is which object the factory returns.

It does not attempt to sound like a model: answers are assembled from the
grounded context the caller already computed, which keeps them factually
consistent with the dashboard while making it obvious in a demo that this is the
mock rather than live inference.
"""

from __future__ import annotations

import asyncio
import json
import re
from typing import AsyncIterator

#: Rough pacing for the streaming path, so the UI's token-by-token rendering is
#: visible rather than arriving as one instant blob.
_TOKEN_DELAY_SECONDS = 0.02


class MockLlmProvider:
    name = "mock"
    model = "mock-llm-v1"

    async def complete(self, *, system_prompt: str, user_prompt: str, history: list[dict[str, str]] | None = None) -> str:
        await asyncio.sleep(0.15)  # simulate a plausible round-trip
        return _answer(system_prompt, user_prompt)

    async def stream(self, *, system_prompt: str, user_prompt: str, history: list[dict[str, str]] | None = None) -> AsyncIterator[str]:
        text = _answer(system_prompt, user_prompt)
        for token in re.findall(r"\S+\s*", text):
            await asyncio.sleep(_TOKEN_DELAY_SECONDS)
            yield token


def _answer(system_prompt: str, user_prompt: str) -> str:
    """Route on the task marker the prompt builders put in the system prompt."""
    if "TASK: RISK_ASSESSMENT" in system_prompt:
        return _risk_assessment(user_prompt)
    if "TASK: PORTFOLIO_BRIEF" in system_prompt:
        return _portfolio_brief(user_prompt)
    return _copilot(user_prompt)


def _copilot(user_prompt: str) -> str:
    question = _extract(user_prompt, "QUESTION") or "your question"
    context = _extract(user_prompt, "PORTFOLIO CONTEXT") or "(no context supplied)"

    return (
        f"[mock-llm] Answering from the {_describe_scope(context)} currently in view.\n\n"
        f"You asked: {question}\n\n"
        "Based on the portfolio snapshot supplied with this request:\n"
        f"{_bullets(context)}\n\n"
        "Note: this response was generated by the built-in mock provider. Set "
        "CEREBRAS_API_KEY to route the same request through live inference."
    )


def _risk_assessment(user_prompt: str) -> str:
    """Returns the same JSON shape the real model is instructed to produce, so
    the parser downstream is exercised identically either way."""
    premium = _number(user_prompt, r"Premium:\s*([\d.]+)")
    flagged = "Flagged for review: True" in user_prompt
    status = _extract_line(user_prompt, "Status:") or "Unknown"
    expiring = "expiring within 30 days" in user_prompt.lower()

    score = 30
    factors: list[str] = []

    if premium and premium > 1_000_000:
        score += 25
        factors.append("Premium is in the top commercial band, raising single-risk concentration.")
    elif premium and premium < 10_000:
        score += 5
        factors.append("Low premium relative to the book; limited financial exposure.")

    if status.strip() == "Pending":
        score += 15
        factors.append("Policy is still Pending, so binding terms are not finalised.")
    if status.strip() == "Expired":
        score += 10
        factors.append("Policy has expired without a recorded renewal.")

    if expiring:
        score += 15
        factors.append("Expiry falls inside the 30-day renewal window.")
    if flagged:
        score += 10
        factors.append("Already flagged by an operator for manual review.")

    if not factors:
        factors.append("No elevated indicators found in the supplied policy attributes.")

    score = min(score, 95)
    band = "High" if score >= 70 else "Medium" if score >= 45 else "Low"

    return json.dumps(
        {
            "riskScore": score,
            "riskBand": band,
            "factors": factors,
            "recommendation": (
                "Route to a senior underwriter before renewal."
                if band == "High"
                else "Standard review cycle is sufficient."
            ),
            "suggestFlag": band == "High",
            "summary": (
                f"[mock-llm] {band} risk ({score}/100) based on premium band, status and renewal proximity."
            ),
        },
        indent=2,
    )


def _portfolio_brief(user_prompt: str) -> str:
    context = _extract(user_prompt, "PORTFOLIO CONTEXT") or ""
    return (
        "[mock-llm] Portfolio brief\n\n"
        f"{_bullets(context)}\n\n"
        "- Renewal pressure is concentrated in the policies inside the 30-day expiry window; "
        "prioritise those for underwriter outreach.\n"
        "- Flagged volume is the clearest operational backlog signal in this view."
    )


# --------------------------------------------------------------------------- #
# Prompt parsing helpers
# --------------------------------------------------------------------------- #


def _extract(prompt: str, header: str) -> str | None:
    """Pull one `HEADER:` ... block out of a prompt built by app.application.prompts."""
    match = re.search(rf"{re.escape(header)}:\s*\n?(.*?)(?=\n[A-Z][A-Z ]+:|\Z)", prompt, re.DOTALL)
    return match.group(1).strip() if match else None


def _extract_line(prompt: str, label: str) -> str | None:
    match = re.search(rf"{re.escape(label)}\s*(.+)", prompt)
    return match.group(1).strip() if match else None


def _number(prompt: str, pattern: str) -> float | None:
    match = re.search(pattern, prompt)
    return float(match.group(1)) if match else None


def _bullets(context: str, limit: int = 5) -> str:
    lines = [line.strip("- ").strip() for line in context.splitlines() if line.strip()]
    if not lines:
        return "- No portfolio metrics were supplied with this request."
    return "\n".join(f"- {line}" for line in lines[:limit])


def _describe_scope(context: str) -> str:
    match = re.search(r"Total policies in scope:\s*(\d+)", context)
    return f"{match.group(1)} policies" if match else "policy set"
